### ISSUE TITLE
question about GetRAxMLStatsPostAnalysis

### ISSUE THREAD

**Issue by snacktavish** [bbanbury/phrynomics-data#1]
I was curious about how you were getting the tree length for your analyses, and I see it is at:
https://github.com/bbanbury/phrynomics-data/blob/fcb1019e016cf9e725985400c95416ecadf6f59f/phrynomicsFunctions.R#L591
but I don't find "Tree-length" in any of my raxml output files. Did you need a flag to output that, or is it from an older version? Thanks! @rboria00

**Comment by bbanbury** [comment]
Hi there,
I haven't worked with the newer versions of RAxML, so I am not sure if the
info files have changed.  But it used to be reported as a single line in
the info file.  It is possible this went away in the new version.
Barb

______________________
Barb Banbury

**Comment by snacktavish** [comment]
Thanks!

**Comment by lixingguang** [comment]
@could you please help me analysis my dataset, thanks.
